AllCops:
  TargetRubyVersion: 2.4

Metrics/AbcSize:
  Max: 33

Metrics/BlockLength:
  Exclude:
    - spec/*

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 32

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 9

# We'll come back to this.
Style/Documentation:
  Enabled: false
